name: Secret Test

on:
  push:
    branches:
      - main

jobs:
  env:
    runs-on: ubuntu-latest
    outputs:
      test_secret: ${{ steps.step1.outputs.test_secret }}
    steps:
      - id: step1
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        shell: bash
        run: |
          echo "test_secret=$TEST_SECRET" >> $GITHUB_OUTPUT

  use-env:
    needs: [env]
    runs-on: ubuntu-latest
    steps:
      - name: Print test secret
        run: echo ${{ needs.env.outputs.test_secret }}
