name: Secret Test

on:
  push:
    branches:
      - main

jobs:
  env:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.step1.outputs.env }}
    steps:
      - id: step1
        run: |
          echo "env=test" >> $GITHUB_OUTPUT

  use-env:
    needs: [env]
    environment: ${{ needs.env.outputs.env }}
    runs-on: ubuntu-latest
    steps:
      - name: Print test secret
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          echo "$TEST_SECRET"
